name: zec
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11.7
  - snakemake=8.11.1
  - numpy=1.23.5
  - pandas=2.2.0
  - pyam=1.9.0
  - scipy=1.11.4
  - seaborn=0.13.1
  - dask=2023.12.1
  - xarray=2024.1.0
  - netcdf4=1.6.5
  - git=2.34.1
  - pip=23.3.2
  - pip:
    - faceted==0.2.1
    - pooch==1.8.0
  - jupyterlab==4.2.5
